default['packages']['opensuse']['15.4']['repo']['obs_-_Virtualization'] = {
    'autorefresh' => false,
    'description' => 'OBS - Virtualization',
    'enabled' => true,
    'gpgcheck' => true,
    'gpgautoimportkeys' => true,
    'gpgkey' => 'https://download.opensuse.org/repositories/Virtualization/15.4/repodata/repomd.xml.key',
    'keeppackages' => false,
    'name' => 'obs-Virtualization',
    'priority' => 90,
    'type' => 'rpm-md',
    'url' => 'https://download.opensuse.org/repositories/Virtualization/15.4/',
    'file_name' => 'obs_-_Virtualization'
}
default['packages']['opensuse']['15.4']['repo']['obs_-_Virtualization:Containers'] = {
    'autorefresh' => false,
    'description' => 'OBS - Virtualization:Containers',
    'enabled' => true,
    'gpgcheck' => true,
    'gpgautoimportkeys' => true,
    'gpgkey' => 'https://download.opensuse.org/repositories/Virtualization/containers/15.4/repodata/repomd.xml.key',
    'keeppackages' => false,
    'name' => 'obs-Virtualization_Containers',
    'priority' => 90,
    'type' => 'rpm-md',
    'url' => 'https://download.opensuse.org/repositories/Virtualization:/containers/15.4/',
    'file_name' => 'obs_-_Virtualization:Containers'
}
default['packages']['opensuse']['15.4']['repo']['obs_-_Virtualization:Vagrant'] = {
    'autorefresh' => false,
    'description' => 'OBS - Virtualization:Vagrant',
    'enabled' => true,
    'gpgcheck' => true,
    'gpgautoimportkeys' => true,
    'gpgkey' => 'https://download.opensuse.org/repositories/Virtualization:/vagrant/15.4/repodata/repomd.xml.key',
    'keeppackages' => false,
    'name' => 'obs_-_Virtualization:Vagrant',
    'priority' => 90,
    'type' => 'rpm-md',
    'url' => 'https://download.opensuse.org/repositories/Virtualization:/vagrant/15.4/',
    'file_name' => 'obs_-_Virtualization:Vagrant'
}
default['packages']['opensuse']['15.4']['repo']['obs_-_Virtualization:VirtualBox'] = {
    'autorefresh' => false,
    'description' => 'OBS - Virtualization:VirtualBox',
    'enabled' => true,
    'gpgcheck' => true,
    'gpgautoimportkeys' => true,
    'gpgkey' => 'https://download.opensuse.org/repositories/Virtualization:/virtualbox/15.4/repodata/repomd.xml.key',
    'keeppackages' => false,
    'name' => 'obs_-_Virtualization:VirtualBox',
    'priority' => 90,
    'type' => 'rpm-md',
    'url' => 'https://download.opensuse.org/repositories/Virtualization:/virtualbox/15.4/',
    'file_name' => 'obs_-_Virtualization:VirtualBox'
}
